// Code generated by Kitex v0.16.2. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	user "github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/user"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, req *user.RegisterRequest, callOptions ...callopt.Option) (r *user.RegisterResponse, err error)
	Login(ctx context.Context, req *user.LoginRequest, callOptions ...callopt.Option) (r *user.LoginResponse, err error)
	GetProfile(ctx context.Context, req *user.GetProfileRequest, callOptions ...callopt.Option) (r *user.GetProfileResponse, err error)
	UpdateProfile(ctx context.Context, req *user.UpdateProfileRequest, callOptions ...callopt.Option) (r *user.UpdateProfileResponse, err error)
	GetDashboard(ctx context.Context, req *user.GetDashboardRequest, callOptions ...callopt.Option) (r *user.GetDashboardResponse, err error)
	GetPreferences(ctx context.Context, req *user.GetPreferencesRequest, callOptions ...callopt.Option) (r *user.GetPreferencesResponse, err error)
	UpdatePreferences(ctx context.Context, req *user.UpdatePreferencesRequest, callOptions ...callopt.Option) (r *user.UpdatePreferencesResponse, err error)
	GetSettings(ctx context.Context, req *user.GetSettingsRequest, callOptions ...callopt.Option) (r *user.GetSettingsResponse, err error)
	UpdateSettings(ctx context.Context, req *user.UpdateSettingsRequest, callOptions ...callopt.Option) (r *user.UpdateSettingsResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, req *user.RegisterRequest, callOptions ...callopt.Option) (r *user.RegisterResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, req)
}

func (p *kUserServiceClient) Login(ctx context.Context, req *user.LoginRequest, callOptions ...callopt.Option) (r *user.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, req)
}

func (p *kUserServiceClient) GetProfile(ctx context.Context, req *user.GetProfileRequest, callOptions ...callopt.Option) (r *user.GetProfileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetProfile(ctx, req)
}

func (p *kUserServiceClient) UpdateProfile(ctx context.Context, req *user.UpdateProfileRequest, callOptions ...callopt.Option) (r *user.UpdateProfileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProfile(ctx, req)
}

func (p *kUserServiceClient) GetDashboard(ctx context.Context, req *user.GetDashboardRequest, callOptions ...callopt.Option) (r *user.GetDashboardResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDashboard(ctx, req)
}

func (p *kUserServiceClient) GetPreferences(ctx context.Context, req *user.GetPreferencesRequest, callOptions ...callopt.Option) (r *user.GetPreferencesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPreferences(ctx, req)
}

func (p *kUserServiceClient) UpdatePreferences(ctx context.Context, req *user.UpdatePreferencesRequest, callOptions ...callopt.Option) (r *user.UpdatePreferencesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdatePreferences(ctx, req)
}

func (p *kUserServiceClient) GetSettings(ctx context.Context, req *user.GetSettingsRequest, callOptions ...callopt.Option) (r *user.GetSettingsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetSettings(ctx, req)
}

func (p *kUserServiceClient) UpdateSettings(ctx context.Context, req *user.UpdateSettingsRequest, callOptions ...callopt.Option) (r *user.UpdateSettingsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateSettings(ctx, req)
}
