// Code generated by Kitex v0.16.2. DO NOT EDIT.

package userservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	user "github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/user"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Register": kitex.NewMethodInfo(
		registerHandler,
		newUserServiceRegisterArgs,
		newUserServiceRegisterResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Login": kitex.NewMethodInfo(
		loginHandler,
		newUserServiceLoginArgs,
		newUserServiceLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetProfile": kitex.NewMethodInfo(
		getProfileHandler,
		newUserServiceGetProfileArgs,
		newUserServiceGetProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateProfile": kitex.NewMethodInfo(
		updateProfileHandler,
		newUserServiceUpdateProfileArgs,
		newUserServiceUpdateProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetDashboard": kitex.NewMethodInfo(
		getDashboardHandler,
		newUserServiceGetDashboardArgs,
		newUserServiceGetDashboardResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPreferences": kitex.NewMethodInfo(
		getPreferencesHandler,
		newUserServiceGetPreferencesArgs,
		newUserServiceGetPreferencesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdatePreferences": kitex.NewMethodInfo(
		updatePreferencesHandler,
		newUserServiceUpdatePreferencesArgs,
		newUserServiceUpdatePreferencesResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetSettings": kitex.NewMethodInfo(
		getSettingsHandler,
		newUserServiceGetSettingsArgs,
		newUserServiceGetSettingsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateSettings": kitex.NewMethodInfo(
		updateSettingsHandler,
		newUserServiceUpdateSettingsArgs,
		newUserServiceUpdateSettingsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userServiceServiceInfo                = NewServiceInfo()
	userServiceServiceInfoForClient       = NewServiceInfoForClient()
	userServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*user.UserService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "user",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func registerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceRegisterArgs)
	realResult := result.(*user.UserServiceRegisterResult)
	success, err := handler.(user.UserService).Register(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegisterArgs() interface{} {
	return user.NewUserServiceRegisterArgs()
}

func newUserServiceRegisterResult() interface{} {
	return user.NewUserServiceRegisterResult()
}

func loginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceLoginArgs)
	realResult := result.(*user.UserServiceLoginResult)
	success, err := handler.(user.UserService).Login(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginArgs() interface{} {
	return user.NewUserServiceLoginArgs()
}

func newUserServiceLoginResult() interface{} {
	return user.NewUserServiceLoginResult()
}

func getProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetProfileArgs)
	realResult := result.(*user.UserServiceGetProfileResult)
	success, err := handler.(user.UserService).GetProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetProfileArgs() interface{} {
	return user.NewUserServiceGetProfileArgs()
}

func newUserServiceGetProfileResult() interface{} {
	return user.NewUserServiceGetProfileResult()
}

func updateProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateProfileArgs)
	realResult := result.(*user.UserServiceUpdateProfileResult)
	success, err := handler.(user.UserService).UpdateProfile(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateProfileArgs() interface{} {
	return user.NewUserServiceUpdateProfileArgs()
}

func newUserServiceUpdateProfileResult() interface{} {
	return user.NewUserServiceUpdateProfileResult()
}

func getDashboardHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetDashboardArgs)
	realResult := result.(*user.UserServiceGetDashboardResult)
	success, err := handler.(user.UserService).GetDashboard(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetDashboardArgs() interface{} {
	return user.NewUserServiceGetDashboardArgs()
}

func newUserServiceGetDashboardResult() interface{} {
	return user.NewUserServiceGetDashboardResult()
}

func getPreferencesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetPreferencesArgs)
	realResult := result.(*user.UserServiceGetPreferencesResult)
	success, err := handler.(user.UserService).GetPreferences(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetPreferencesArgs() interface{} {
	return user.NewUserServiceGetPreferencesArgs()
}

func newUserServiceGetPreferencesResult() interface{} {
	return user.NewUserServiceGetPreferencesResult()
}

func updatePreferencesHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdatePreferencesArgs)
	realResult := result.(*user.UserServiceUpdatePreferencesResult)
	success, err := handler.(user.UserService).UpdatePreferences(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdatePreferencesArgs() interface{} {
	return user.NewUserServiceUpdatePreferencesArgs()
}

func newUserServiceUpdatePreferencesResult() interface{} {
	return user.NewUserServiceUpdatePreferencesResult()
}

func getSettingsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceGetSettingsArgs)
	realResult := result.(*user.UserServiceGetSettingsResult)
	success, err := handler.(user.UserService).GetSettings(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceGetSettingsArgs() interface{} {
	return user.NewUserServiceGetSettingsArgs()
}

func newUserServiceGetSettingsResult() interface{} {
	return user.NewUserServiceGetSettingsResult()
}

func updateSettingsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*user.UserServiceUpdateSettingsArgs)
	realResult := result.(*user.UserServiceUpdateSettingsResult)
	success, err := handler.(user.UserService).UpdateSettings(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceUpdateSettingsArgs() interface{} {
	return user.NewUserServiceUpdateSettingsArgs()
}

func newUserServiceUpdateSettingsResult() interface{} {
	return user.NewUserServiceUpdateSettingsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Register(ctx context.Context, req *user.RegisterRequest) (r *user.RegisterResponse, err error) {
	var _args user.UserServiceRegisterArgs
	_args.Req = req
	var _result user.UserServiceRegisterResult
	if err = p.c.Call(ctx, "Register", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Login(ctx context.Context, req *user.LoginRequest) (r *user.LoginResponse, err error) {
	var _args user.UserServiceLoginArgs
	_args.Req = req
	var _result user.UserServiceLoginResult
	if err = p.c.Call(ctx, "Login", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetProfile(ctx context.Context, req *user.GetProfileRequest) (r *user.GetProfileResponse, err error) {
	var _args user.UserServiceGetProfileArgs
	_args.Req = req
	var _result user.UserServiceGetProfileResult
	if err = p.c.Call(ctx, "GetProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateProfile(ctx context.Context, req *user.UpdateProfileRequest) (r *user.UpdateProfileResponse, err error) {
	var _args user.UserServiceUpdateProfileArgs
	_args.Req = req
	var _result user.UserServiceUpdateProfileResult
	if err = p.c.Call(ctx, "UpdateProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDashboard(ctx context.Context, req *user.GetDashboardRequest) (r *user.GetDashboardResponse, err error) {
	var _args user.UserServiceGetDashboardArgs
	_args.Req = req
	var _result user.UserServiceGetDashboardResult
	if err = p.c.Call(ctx, "GetDashboard", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPreferences(ctx context.Context, req *user.GetPreferencesRequest) (r *user.GetPreferencesResponse, err error) {
	var _args user.UserServiceGetPreferencesArgs
	_args.Req = req
	var _result user.UserServiceGetPreferencesResult
	if err = p.c.Call(ctx, "GetPreferences", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdatePreferences(ctx context.Context, req *user.UpdatePreferencesRequest) (r *user.UpdatePreferencesResponse, err error) {
	var _args user.UserServiceUpdatePreferencesArgs
	_args.Req = req
	var _result user.UserServiceUpdatePreferencesResult
	if err = p.c.Call(ctx, "UpdatePreferences", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetSettings(ctx context.Context, req *user.GetSettingsRequest) (r *user.GetSettingsResponse, err error) {
	var _args user.UserServiceGetSettingsArgs
	_args.Req = req
	var _result user.UserServiceGetSettingsResult
	if err = p.c.Call(ctx, "GetSettings", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateSettings(ctx context.Context, req *user.UpdateSettingsRequest) (r *user.UpdateSettingsResponse, err error) {
	var _args user.UserServiceUpdateSettingsArgs
	_args.Req = req
	var _result user.UserServiceUpdateSettingsResult
	if err = p.c.Call(ctx, "UpdateSettings", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
