// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package trip

import (
	"context"
	"fmt"
	"github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/base"
)

type TripSummary struct {
	Date   *string `thrift:"date,1,optional" frugal:"1,optional,string" json:"date,omitempty"`
	Days   *string `thrift:"days,2,optional" frugal:"2,optional,string" json:"days,omitempty"`
	People *string `thrift:"people,3,optional" frugal:"3,optional,string" json:"people,omitempty"`
	Budget *string `thrift:"budget,4,optional" frugal:"4,optional,string" json:"budget,omitempty"`
}

func NewTripSummary() *TripSummary {
	return &TripSummary{}
}

func (p *TripSummary) InitDefault() {
}

var TripSummary_Date_DEFAULT string

func (p *TripSummary) GetDate() (v string) {
	if !p.IsSetDate() {
		return TripSummary_Date_DEFAULT
	}
	return *p.Date
}

var TripSummary_Days_DEFAULT string

func (p *TripSummary) GetDays() (v string) {
	if !p.IsSetDays() {
		return TripSummary_Days_DEFAULT
	}
	return *p.Days
}

var TripSummary_People_DEFAULT string

func (p *TripSummary) GetPeople() (v string) {
	if !p.IsSetPeople() {
		return TripSummary_People_DEFAULT
	}
	return *p.People
}

var TripSummary_Budget_DEFAULT string

func (p *TripSummary) GetBudget() (v string) {
	if !p.IsSetBudget() {
		return TripSummary_Budget_DEFAULT
	}
	return *p.Budget
}
func (p *TripSummary) SetDate(val *string) {
	p.Date = val
}
func (p *TripSummary) SetDays(val *string) {
	p.Days = val
}
func (p *TripSummary) SetPeople(val *string) {
	p.People = val
}
func (p *TripSummary) SetBudget(val *string) {
	p.Budget = val
}

func (p *TripSummary) IsSetDate() bool {
	return p.Date != nil
}

func (p *TripSummary) IsSetDays() bool {
	return p.Days != nil
}

func (p *TripSummary) IsSetPeople() bool {
	return p.People != nil
}

func (p *TripSummary) IsSetBudget() bool {
	return p.Budget != nil
}

func (p *TripSummary) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripSummary(%+v)", *p)
}

var fieldIDToName_TripSummary = map[int16]string{
	1: "date",
	2: "days",
	3: "people",
	4: "budget",
}

type TripTip struct {
	Icon  *string `thrift:"icon,1,optional" frugal:"1,optional,string" json:"icon,omitempty"`
	Title *string `thrift:"title,2,optional" frugal:"2,optional,string" json:"title,omitempty"`
	Text  *string `thrift:"text,3,optional" frugal:"3,optional,string" json:"text,omitempty"`
}

func NewTripTip() *TripTip {
	return &TripTip{}
}

func (p *TripTip) InitDefault() {
}

var TripTip_Icon_DEFAULT string

func (p *TripTip) GetIcon() (v string) {
	if !p.IsSetIcon() {
		return TripTip_Icon_DEFAULT
	}
	return *p.Icon
}

var TripTip_Title_DEFAULT string

func (p *TripTip) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return TripTip_Title_DEFAULT
	}
	return *p.Title
}

var TripTip_Text_DEFAULT string

func (p *TripTip) GetText() (v string) {
	if !p.IsSetText() {
		return TripTip_Text_DEFAULT
	}
	return *p.Text
}
func (p *TripTip) SetIcon(val *string) {
	p.Icon = val
}
func (p *TripTip) SetTitle(val *string) {
	p.Title = val
}
func (p *TripTip) SetText(val *string) {
	p.Text = val
}

func (p *TripTip) IsSetIcon() bool {
	return p.Icon != nil
}

func (p *TripTip) IsSetTitle() bool {
	return p.Title != nil
}

func (p *TripTip) IsSetText() bool {
	return p.Text != nil
}

func (p *TripTip) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripTip(%+v)", *p)
}

var fieldIDToName_TripTip = map[int16]string{
	1: "icon",
	2: "title",
	3: "text",
}

type TripDay struct {
	Day     int32      `thrift:"day,1,required" frugal:"1,required,i32" json:"day"`
	Title   *string    `thrift:"title,2,optional" frugal:"2,optional,string" json:"title,omitempty"`
	Route   *string    `thrift:"route,3,optional" frugal:"3,optional,string" json:"route,omitempty"`
	Food    *string    `thrift:"food,4,optional" frugal:"4,optional,string" json:"food,omitempty"`
	Hotel   *string    `thrift:"hotel,5,optional" frugal:"5,optional,string" json:"hotel,omitempty"`
	Tips    []*TripTip `thrift:"tips,6,optional" frugal:"6,optional,list<TripTip>" json:"tips,omitempty"`
	Weather *string    `thrift:"weather,7,optional" frugal:"7,optional,string" json:"weather,omitempty"`
}

func NewTripDay() *TripDay {
	return &TripDay{}
}

func (p *TripDay) InitDefault() {
}

func (p *TripDay) GetDay() (v int32) {
	return p.Day
}

var TripDay_Title_DEFAULT string

func (p *TripDay) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return TripDay_Title_DEFAULT
	}
	return *p.Title
}

var TripDay_Route_DEFAULT string

func (p *TripDay) GetRoute() (v string) {
	if !p.IsSetRoute() {
		return TripDay_Route_DEFAULT
	}
	return *p.Route
}

var TripDay_Food_DEFAULT string

func (p *TripDay) GetFood() (v string) {
	if !p.IsSetFood() {
		return TripDay_Food_DEFAULT
	}
	return *p.Food
}

var TripDay_Hotel_DEFAULT string

func (p *TripDay) GetHotel() (v string) {
	if !p.IsSetHotel() {
		return TripDay_Hotel_DEFAULT
	}
	return *p.Hotel
}

var TripDay_Tips_DEFAULT []*TripTip

func (p *TripDay) GetTips() (v []*TripTip) {
	if !p.IsSetTips() {
		return TripDay_Tips_DEFAULT
	}
	return p.Tips
}

var TripDay_Weather_DEFAULT string

func (p *TripDay) GetWeather() (v string) {
	if !p.IsSetWeather() {
		return TripDay_Weather_DEFAULT
	}
	return *p.Weather
}
func (p *TripDay) SetDay(val int32) {
	p.Day = val
}
func (p *TripDay) SetTitle(val *string) {
	p.Title = val
}
func (p *TripDay) SetRoute(val *string) {
	p.Route = val
}
func (p *TripDay) SetFood(val *string) {
	p.Food = val
}
func (p *TripDay) SetHotel(val *string) {
	p.Hotel = val
}
func (p *TripDay) SetTips(val []*TripTip) {
	p.Tips = val
}
func (p *TripDay) SetWeather(val *string) {
	p.Weather = val
}

func (p *TripDay) IsSetTitle() bool {
	return p.Title != nil
}

func (p *TripDay) IsSetRoute() bool {
	return p.Route != nil
}

func (p *TripDay) IsSetFood() bool {
	return p.Food != nil
}

func (p *TripDay) IsSetHotel() bool {
	return p.Hotel != nil
}

func (p *TripDay) IsSetTips() bool {
	return p.Tips != nil
}

func (p *TripDay) IsSetWeather() bool {
	return p.Weather != nil
}

func (p *TripDay) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripDay(%+v)", *p)
}

var fieldIDToName_TripDay = map[int16]string{
	1: "day",
	2: "title",
	3: "route",
	4: "food",
	5: "hotel",
	6: "tips",
	7: "weather",
}

type TripBudget struct {
	Label  *string `thrift:"label,1,optional" frugal:"1,optional,string" json:"label,omitempty"`
	Amount *string `thrift:"amount,2,optional" frugal:"2,optional,string" json:"amount,omitempty"`
}

func NewTripBudget() *TripBudget {
	return &TripBudget{}
}

func (p *TripBudget) InitDefault() {
}

var TripBudget_Label_DEFAULT string

func (p *TripBudget) GetLabel() (v string) {
	if !p.IsSetLabel() {
		return TripBudget_Label_DEFAULT
	}
	return *p.Label
}

var TripBudget_Amount_DEFAULT string

func (p *TripBudget) GetAmount() (v string) {
	if !p.IsSetAmount() {
		return TripBudget_Amount_DEFAULT
	}
	return *p.Amount
}
func (p *TripBudget) SetLabel(val *string) {
	p.Label = val
}
func (p *TripBudget) SetAmount(val *string) {
	p.Amount = val
}

func (p *TripBudget) IsSetLabel() bool {
	return p.Label != nil
}

func (p *TripBudget) IsSetAmount() bool {
	return p.Amount != nil
}

func (p *TripBudget) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripBudget(%+v)", *p)
}

var fieldIDToName_TripBudget = map[int16]string{
	1: "label",
	2: "amount",
}

type TripInfo struct {
	Id             string        `thrift:"id,1,required" frugal:"1,required,string" json:"id"`
	UserId         int64         `thrift:"userId,2,required" frugal:"2,required,i64" json:"userId"`
	Title          string        `thrift:"title,3,required" frugal:"3,required,string" json:"title"`
	Subtitle       *string       `thrift:"subtitle,4,optional" frugal:"4,optional,string" json:"subtitle,omitempty"`
	Destination    *string       `thrift:"destination,5,optional" frugal:"5,optional,string" json:"destination,omitempty"`
	DateRange      *string       `thrift:"dateRange,6,optional" frugal:"6,optional,string" json:"dateRange,omitempty"`
	DayCount       *int32        `thrift:"dayCount,7,optional" frugal:"7,optional,i32" json:"dayCount,omitempty"`
	People         *string       `thrift:"people,8,optional" frugal:"8,optional,string" json:"people,omitempty"`
	BudgetLevel    *string       `thrift:"budgetLevel,9,optional" frugal:"9,optional,string" json:"budgetLevel,omitempty"`
	SourceQuestion *string       `thrift:"sourceQuestion,10,optional" frugal:"10,optional,string" json:"sourceQuestion,omitempty"`
	SourceReply    *string       `thrift:"sourceReply,11,optional" frugal:"11,optional,string" json:"sourceReply,omitempty"`
	Summary        *TripSummary  `thrift:"summary,12,optional" frugal:"12,optional,TripSummary" json:"summary,omitempty"`
	Days           []*TripDay    `thrift:"days,13,optional" frugal:"13,optional,list<TripDay>" json:"days,omitempty"`
	Budget         []*TripBudget `thrift:"budget,14,optional" frugal:"14,optional,list<TripBudget>" json:"budget,omitempty"`
	Alerts         []string      `thrift:"alerts,15,optional" frugal:"15,optional,list<string>" json:"alerts,omitempty"`
	Saved          bool          `thrift:"saved,16,required" frugal:"16,required,bool" json:"saved"`
	CreatedAt      *string       `thrift:"createdAt,17,optional" frugal:"17,optional,string" json:"createdAt,omitempty"`
	UpdatedAt      *string       `thrift:"updatedAt,18,optional" frugal:"18,optional,string" json:"updatedAt,omitempty"`
}

func NewTripInfo() *TripInfo {
	return &TripInfo{}
}

func (p *TripInfo) InitDefault() {
}

func (p *TripInfo) GetId() (v string) {
	return p.Id
}

func (p *TripInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *TripInfo) GetTitle() (v string) {
	return p.Title
}

var TripInfo_Subtitle_DEFAULT string

func (p *TripInfo) GetSubtitle() (v string) {
	if !p.IsSetSubtitle() {
		return TripInfo_Subtitle_DEFAULT
	}
	return *p.Subtitle
}

var TripInfo_Destination_DEFAULT string

func (p *TripInfo) GetDestination() (v string) {
	if !p.IsSetDestination() {
		return TripInfo_Destination_DEFAULT
	}
	return *p.Destination
}

var TripInfo_DateRange_DEFAULT string

func (p *TripInfo) GetDateRange() (v string) {
	if !p.IsSetDateRange() {
		return TripInfo_DateRange_DEFAULT
	}
	return *p.DateRange
}

var TripInfo_DayCount_DEFAULT int32

func (p *TripInfo) GetDayCount() (v int32) {
	if !p.IsSetDayCount() {
		return TripInfo_DayCount_DEFAULT
	}
	return *p.DayCount
}

var TripInfo_People_DEFAULT string

func (p *TripInfo) GetPeople() (v string) {
	if !p.IsSetPeople() {
		return TripInfo_People_DEFAULT
	}
	return *p.People
}

var TripInfo_BudgetLevel_DEFAULT string

func (p *TripInfo) GetBudgetLevel() (v string) {
	if !p.IsSetBudgetLevel() {
		return TripInfo_BudgetLevel_DEFAULT
	}
	return *p.BudgetLevel
}

var TripInfo_SourceQuestion_DEFAULT string

func (p *TripInfo) GetSourceQuestion() (v string) {
	if !p.IsSetSourceQuestion() {
		return TripInfo_SourceQuestion_DEFAULT
	}
	return *p.SourceQuestion
}

var TripInfo_SourceReply_DEFAULT string

func (p *TripInfo) GetSourceReply() (v string) {
	if !p.IsSetSourceReply() {
		return TripInfo_SourceReply_DEFAULT
	}
	return *p.SourceReply
}

var TripInfo_Summary_DEFAULT *TripSummary

func (p *TripInfo) GetSummary() (v *TripSummary) {
	if !p.IsSetSummary() {
		return TripInfo_Summary_DEFAULT
	}
	return p.Summary
}

var TripInfo_Days_DEFAULT []*TripDay

func (p *TripInfo) GetDays() (v []*TripDay) {
	if !p.IsSetDays() {
		return TripInfo_Days_DEFAULT
	}
	return p.Days
}

var TripInfo_Budget_DEFAULT []*TripBudget

func (p *TripInfo) GetBudget() (v []*TripBudget) {
	if !p.IsSetBudget() {
		return TripInfo_Budget_DEFAULT
	}
	return p.Budget
}

var TripInfo_Alerts_DEFAULT []string

func (p *TripInfo) GetAlerts() (v []string) {
	if !p.IsSetAlerts() {
		return TripInfo_Alerts_DEFAULT
	}
	return p.Alerts
}

func (p *TripInfo) GetSaved() (v bool) {
	return p.Saved
}

var TripInfo_CreatedAt_DEFAULT string

func (p *TripInfo) GetCreatedAt() (v string) {
	if !p.IsSetCreatedAt() {
		return TripInfo_CreatedAt_DEFAULT
	}
	return *p.CreatedAt
}

var TripInfo_UpdatedAt_DEFAULT string

func (p *TripInfo) GetUpdatedAt() (v string) {
	if !p.IsSetUpdatedAt() {
		return TripInfo_UpdatedAt_DEFAULT
	}
	return *p.UpdatedAt
}
func (p *TripInfo) SetId(val string) {
	p.Id = val
}
func (p *TripInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *TripInfo) SetTitle(val string) {
	p.Title = val
}
func (p *TripInfo) SetSubtitle(val *string) {
	p.Subtitle = val
}
func (p *TripInfo) SetDestination(val *string) {
	p.Destination = val
}
func (p *TripInfo) SetDateRange(val *string) {
	p.DateRange = val
}
func (p *TripInfo) SetDayCount(val *int32) {
	p.DayCount = val
}
func (p *TripInfo) SetPeople(val *string) {
	p.People = val
}
func (p *TripInfo) SetBudgetLevel(val *string) {
	p.BudgetLevel = val
}
func (p *TripInfo) SetSourceQuestion(val *string) {
	p.SourceQuestion = val
}
func (p *TripInfo) SetSourceReply(val *string) {
	p.SourceReply = val
}
func (p *TripInfo) SetSummary(val *TripSummary) {
	p.Summary = val
}
func (p *TripInfo) SetDays(val []*TripDay) {
	p.Days = val
}
func (p *TripInfo) SetBudget(val []*TripBudget) {
	p.Budget = val
}
func (p *TripInfo) SetAlerts(val []string) {
	p.Alerts = val
}
func (p *TripInfo) SetSaved(val bool) {
	p.Saved = val
}
func (p *TripInfo) SetCreatedAt(val *string) {
	p.CreatedAt = val
}
func (p *TripInfo) SetUpdatedAt(val *string) {
	p.UpdatedAt = val
}

func (p *TripInfo) IsSetSubtitle() bool {
	return p.Subtitle != nil
}

func (p *TripInfo) IsSetDestination() bool {
	return p.Destination != nil
}

func (p *TripInfo) IsSetDateRange() bool {
	return p.DateRange != nil
}

func (p *TripInfo) IsSetDayCount() bool {
	return p.DayCount != nil
}

func (p *TripInfo) IsSetPeople() bool {
	return p.People != nil
}

func (p *TripInfo) IsSetBudgetLevel() bool {
	return p.BudgetLevel != nil
}

func (p *TripInfo) IsSetSourceQuestion() bool {
	return p.SourceQuestion != nil
}

func (p *TripInfo) IsSetSourceReply() bool {
	return p.SourceReply != nil
}

func (p *TripInfo) IsSetSummary() bool {
	return p.Summary != nil
}

func (p *TripInfo) IsSetDays() bool {
	return p.Days != nil
}

func (p *TripInfo) IsSetBudget() bool {
	return p.Budget != nil
}

func (p *TripInfo) IsSetAlerts() bool {
	return p.Alerts != nil
}

func (p *TripInfo) IsSetCreatedAt() bool {
	return p.CreatedAt != nil
}

func (p *TripInfo) IsSetUpdatedAt() bool {
	return p.UpdatedAt != nil
}

func (p *TripInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripInfo(%+v)", *p)
}

var fieldIDToName_TripInfo = map[int16]string{
	1:  "id",
	2:  "userId",
	3:  "title",
	4:  "subtitle",
	5:  "destination",
	6:  "dateRange",
	7:  "dayCount",
	8:  "people",
	9:  "budgetLevel",
	10: "sourceQuestion",
	11: "sourceReply",
	12: "summary",
	13: "days",
	14: "budget",
	15: "alerts",
	16: "saved",
	17: "createdAt",
	18: "updatedAt",
}

type CreateTripRequest struct {
	UserId         int64         `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	Title          *string       `thrift:"title,2,optional" frugal:"2,optional,string" json:"title,omitempty"`
	Subtitle       *string       `thrift:"subtitle,3,optional" frugal:"3,optional,string" json:"subtitle,omitempty"`
	Destination    *string       `thrift:"destination,4,optional" frugal:"4,optional,string" json:"destination,omitempty"`
	DateRange      *string       `thrift:"dateRange,5,optional" frugal:"5,optional,string" json:"dateRange,omitempty"`
	DayCount       *int32        `thrift:"dayCount,6,optional" frugal:"6,optional,i32" json:"dayCount,omitempty"`
	People         *string       `thrift:"people,7,optional" frugal:"7,optional,string" json:"people,omitempty"`
	BudgetLevel    *string       `thrift:"budgetLevel,8,optional" frugal:"8,optional,string" json:"budgetLevel,omitempty"`
	SourceQuestion *string       `thrift:"sourceQuestion,9,optional" frugal:"9,optional,string" json:"sourceQuestion,omitempty"`
	SourceReply    *string       `thrift:"sourceReply,10,optional" frugal:"10,optional,string" json:"sourceReply,omitempty"`
	Summary        *TripSummary  `thrift:"summary,11,optional" frugal:"11,optional,TripSummary" json:"summary,omitempty"`
	Days           []*TripDay    `thrift:"days,12,optional" frugal:"12,optional,list<TripDay>" json:"days,omitempty"`
	Budget         []*TripBudget `thrift:"budget,13,optional" frugal:"13,optional,list<TripBudget>" json:"budget,omitempty"`
	Alerts         []string      `thrift:"alerts,14,optional" frugal:"14,optional,list<string>" json:"alerts,omitempty"`
}

func NewCreateTripRequest() *CreateTripRequest {
	return &CreateTripRequest{}
}

func (p *CreateTripRequest) InitDefault() {
}

func (p *CreateTripRequest) GetUserId() (v int64) {
	return p.UserId
}

var CreateTripRequest_Title_DEFAULT string

func (p *CreateTripRequest) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return CreateTripRequest_Title_DEFAULT
	}
	return *p.Title
}

var CreateTripRequest_Subtitle_DEFAULT string

func (p *CreateTripRequest) GetSubtitle() (v string) {
	if !p.IsSetSubtitle() {
		return CreateTripRequest_Subtitle_DEFAULT
	}
	return *p.Subtitle
}

var CreateTripRequest_Destination_DEFAULT string

func (p *CreateTripRequest) GetDestination() (v string) {
	if !p.IsSetDestination() {
		return CreateTripRequest_Destination_DEFAULT
	}
	return *p.Destination
}

var CreateTripRequest_DateRange_DEFAULT string

func (p *CreateTripRequest) GetDateRange() (v string) {
	if !p.IsSetDateRange() {
		return CreateTripRequest_DateRange_DEFAULT
	}
	return *p.DateRange
}

var CreateTripRequest_DayCount_DEFAULT int32

func (p *CreateTripRequest) GetDayCount() (v int32) {
	if !p.IsSetDayCount() {
		return CreateTripRequest_DayCount_DEFAULT
	}
	return *p.DayCount
}

var CreateTripRequest_People_DEFAULT string

func (p *CreateTripRequest) GetPeople() (v string) {
	if !p.IsSetPeople() {
		return CreateTripRequest_People_DEFAULT
	}
	return *p.People
}

var CreateTripRequest_BudgetLevel_DEFAULT string

func (p *CreateTripRequest) GetBudgetLevel() (v string) {
	if !p.IsSetBudgetLevel() {
		return CreateTripRequest_BudgetLevel_DEFAULT
	}
	return *p.BudgetLevel
}

var CreateTripRequest_SourceQuestion_DEFAULT string

func (p *CreateTripRequest) GetSourceQuestion() (v string) {
	if !p.IsSetSourceQuestion() {
		return CreateTripRequest_SourceQuestion_DEFAULT
	}
	return *p.SourceQuestion
}

var CreateTripRequest_SourceReply_DEFAULT string

func (p *CreateTripRequest) GetSourceReply() (v string) {
	if !p.IsSetSourceReply() {
		return CreateTripRequest_SourceReply_DEFAULT
	}
	return *p.SourceReply
}

var CreateTripRequest_Summary_DEFAULT *TripSummary

func (p *CreateTripRequest) GetSummary() (v *TripSummary) {
	if !p.IsSetSummary() {
		return CreateTripRequest_Summary_DEFAULT
	}
	return p.Summary
}

var CreateTripRequest_Days_DEFAULT []*TripDay

func (p *CreateTripRequest) GetDays() (v []*TripDay) {
	if !p.IsSetDays() {
		return CreateTripRequest_Days_DEFAULT
	}
	return p.Days
}

var CreateTripRequest_Budget_DEFAULT []*TripBudget

func (p *CreateTripRequest) GetBudget() (v []*TripBudget) {
	if !p.IsSetBudget() {
		return CreateTripRequest_Budget_DEFAULT
	}
	return p.Budget
}

var CreateTripRequest_Alerts_DEFAULT []string

func (p *CreateTripRequest) GetAlerts() (v []string) {
	if !p.IsSetAlerts() {
		return CreateTripRequest_Alerts_DEFAULT
	}
	return p.Alerts
}
func (p *CreateTripRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *CreateTripRequest) SetTitle(val *string) {
	p.Title = val
}
func (p *CreateTripRequest) SetSubtitle(val *string) {
	p.Subtitle = val
}
func (p *CreateTripRequest) SetDestination(val *string) {
	p.Destination = val
}
func (p *CreateTripRequest) SetDateRange(val *string) {
	p.DateRange = val
}
func (p *CreateTripRequest) SetDayCount(val *int32) {
	p.DayCount = val
}
func (p *CreateTripRequest) SetPeople(val *string) {
	p.People = val
}
func (p *CreateTripRequest) SetBudgetLevel(val *string) {
	p.BudgetLevel = val
}
func (p *CreateTripRequest) SetSourceQuestion(val *string) {
	p.SourceQuestion = val
}
func (p *CreateTripRequest) SetSourceReply(val *string) {
	p.SourceReply = val
}
func (p *CreateTripRequest) SetSummary(val *TripSummary) {
	p.Summary = val
}
func (p *CreateTripRequest) SetDays(val []*TripDay) {
	p.Days = val
}
func (p *CreateTripRequest) SetBudget(val []*TripBudget) {
	p.Budget = val
}
func (p *CreateTripRequest) SetAlerts(val []string) {
	p.Alerts = val
}

func (p *CreateTripRequest) IsSetTitle() bool {
	return p.Title != nil
}

func (p *CreateTripRequest) IsSetSubtitle() bool {
	return p.Subtitle != nil
}

func (p *CreateTripRequest) IsSetDestination() bool {
	return p.Destination != nil
}

func (p *CreateTripRequest) IsSetDateRange() bool {
	return p.DateRange != nil
}

func (p *CreateTripRequest) IsSetDayCount() bool {
	return p.DayCount != nil
}

func (p *CreateTripRequest) IsSetPeople() bool {
	return p.People != nil
}

func (p *CreateTripRequest) IsSetBudgetLevel() bool {
	return p.BudgetLevel != nil
}

func (p *CreateTripRequest) IsSetSourceQuestion() bool {
	return p.SourceQuestion != nil
}

func (p *CreateTripRequest) IsSetSourceReply() bool {
	return p.SourceReply != nil
}

func (p *CreateTripRequest) IsSetSummary() bool {
	return p.Summary != nil
}

func (p *CreateTripRequest) IsSetDays() bool {
	return p.Days != nil
}

func (p *CreateTripRequest) IsSetBudget() bool {
	return p.Budget != nil
}

func (p *CreateTripRequest) IsSetAlerts() bool {
	return p.Alerts != nil
}

func (p *CreateTripRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateTripRequest(%+v)", *p)
}

var fieldIDToName_CreateTripRequest = map[int16]string{
	1:  "userId",
	2:  "title",
	3:  "subtitle",
	4:  "destination",
	5:  "dateRange",
	6:  "dayCount",
	7:  "people",
	8:  "budgetLevel",
	9:  "sourceQuestion",
	10: "sourceReply",
	11: "summary",
	12: "days",
	13: "budget",
	14: "alerts",
}

type CreateTripResponse struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1,required" frugal:"1,required,base.BaseResp" json:"baseResp"`
	Trip     *TripInfo      `thrift:"trip,2,optional" frugal:"2,optional,TripInfo" json:"trip,omitempty"`
}

func NewCreateTripResponse() *CreateTripResponse {
	return &CreateTripResponse{}
}

func (p *CreateTripResponse) InitDefault() {
}

var CreateTripResponse_BaseResp_DEFAULT *base.BaseResp

func (p *CreateTripResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateTripResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var CreateTripResponse_Trip_DEFAULT *TripInfo

func (p *CreateTripResponse) GetTrip() (v *TripInfo) {
	if !p.IsSetTrip() {
		return CreateTripResponse_Trip_DEFAULT
	}
	return p.Trip
}
func (p *CreateTripResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *CreateTripResponse) SetTrip(val *TripInfo) {
	p.Trip = val
}

func (p *CreateTripResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateTripResponse) IsSetTrip() bool {
	return p.Trip != nil
}

func (p *CreateTripResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateTripResponse(%+v)", *p)
}

var fieldIDToName_CreateTripResponse = map[int16]string{
	1: "baseResp",
	2: "trip",
}

type ListTripsRequest struct {
	UserId int64  `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	Limit  *int32 `thrift:"limit,2,optional" frugal:"2,optional,i32" json:"limit,omitempty"`
}

func NewListTripsRequest() *ListTripsRequest {
	return &ListTripsRequest{}
}

func (p *ListTripsRequest) InitDefault() {
}

func (p *ListTripsRequest) GetUserId() (v int64) {
	return p.UserId
}

var ListTripsRequest_Limit_DEFAULT int32

func (p *ListTripsRequest) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return ListTripsRequest_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *ListTripsRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ListTripsRequest) SetLimit(val *int32) {
	p.Limit = val
}

func (p *ListTripsRequest) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListTripsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListTripsRequest(%+v)", *p)
}

var fieldIDToName_ListTripsRequest = map[int16]string{
	1: "userId",
	2: "limit",
}

type ListTripsResponse struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1,required" frugal:"1,required,base.BaseResp" json:"baseResp"`
	Trips    []*TripInfo    `thrift:"trips,2,optional" frugal:"2,optional,list<TripInfo>" json:"trips,omitempty"`
}

func NewListTripsResponse() *ListTripsResponse {
	return &ListTripsResponse{}
}

func (p *ListTripsResponse) InitDefault() {
}

var ListTripsResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ListTripsResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListTripsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var ListTripsResponse_Trips_DEFAULT []*TripInfo

func (p *ListTripsResponse) GetTrips() (v []*TripInfo) {
	if !p.IsSetTrips() {
		return ListTripsResponse_Trips_DEFAULT
	}
	return p.Trips
}
func (p *ListTripsResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *ListTripsResponse) SetTrips(val []*TripInfo) {
	p.Trips = val
}

func (p *ListTripsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListTripsResponse) IsSetTrips() bool {
	return p.Trips != nil
}

func (p *ListTripsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListTripsResponse(%+v)", *p)
}

var fieldIDToName_ListTripsResponse = map[int16]string{
	1: "baseResp",
	2: "trips",
}

type GetLatestTripRequest struct {
	UserId int64 `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
}

func NewGetLatestTripRequest() *GetLatestTripRequest {
	return &GetLatestTripRequest{}
}

func (p *GetLatestTripRequest) InitDefault() {
}

func (p *GetLatestTripRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *GetLatestTripRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *GetLatestTripRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLatestTripRequest(%+v)", *p)
}

var fieldIDToName_GetLatestTripRequest = map[int16]string{
	1: "userId",
}

type GetLatestTripResponse struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1,required" frugal:"1,required,base.BaseResp" json:"baseResp"`
	Trip     *TripInfo      `thrift:"trip,2,optional" frugal:"2,optional,TripInfo" json:"trip,omitempty"`
}

func NewGetLatestTripResponse() *GetLatestTripResponse {
	return &GetLatestTripResponse{}
}

func (p *GetLatestTripResponse) InitDefault() {
}

var GetLatestTripResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetLatestTripResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetLatestTripResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetLatestTripResponse_Trip_DEFAULT *TripInfo

func (p *GetLatestTripResponse) GetTrip() (v *TripInfo) {
	if !p.IsSetTrip() {
		return GetLatestTripResponse_Trip_DEFAULT
	}
	return p.Trip
}
func (p *GetLatestTripResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *GetLatestTripResponse) SetTrip(val *TripInfo) {
	p.Trip = val
}

func (p *GetLatestTripResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetLatestTripResponse) IsSetTrip() bool {
	return p.Trip != nil
}

func (p *GetLatestTripResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLatestTripResponse(%+v)", *p)
}

var fieldIDToName_GetLatestTripResponse = map[int16]string{
	1: "baseResp",
	2: "trip",
}

type GetTripDetailRequest struct {
	UserId int64  `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	TripId string `thrift:"tripId,2,required" frugal:"2,required,string" json:"tripId"`
}

func NewGetTripDetailRequest() *GetTripDetailRequest {
	return &GetTripDetailRequest{}
}

func (p *GetTripDetailRequest) InitDefault() {
}

func (p *GetTripDetailRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *GetTripDetailRequest) GetTripId() (v string) {
	return p.TripId
}
func (p *GetTripDetailRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *GetTripDetailRequest) SetTripId(val string) {
	p.TripId = val
}

func (p *GetTripDetailRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTripDetailRequest(%+v)", *p)
}

var fieldIDToName_GetTripDetailRequest = map[int16]string{
	1: "userId",
	2: "tripId",
}

type GetTripDetailResponse struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1,required" frugal:"1,required,base.BaseResp" json:"baseResp"`
	Trip     *TripInfo      `thrift:"trip,2,optional" frugal:"2,optional,TripInfo" json:"trip,omitempty"`
}

func NewGetTripDetailResponse() *GetTripDetailResponse {
	return &GetTripDetailResponse{}
}

func (p *GetTripDetailResponse) InitDefault() {
}

var GetTripDetailResponse_BaseResp_DEFAULT *base.BaseResp

func (p *GetTripDetailResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetTripDetailResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var GetTripDetailResponse_Trip_DEFAULT *TripInfo

func (p *GetTripDetailResponse) GetTrip() (v *TripInfo) {
	if !p.IsSetTrip() {
		return GetTripDetailResponse_Trip_DEFAULT
	}
	return p.Trip
}
func (p *GetTripDetailResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *GetTripDetailResponse) SetTrip(val *TripInfo) {
	p.Trip = val
}

func (p *GetTripDetailResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetTripDetailResponse) IsSetTrip() bool {
	return p.Trip != nil
}

func (p *GetTripDetailResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTripDetailResponse(%+v)", *p)
}

var fieldIDToName_GetTripDetailResponse = map[int16]string{
	1: "baseResp",
	2: "trip",
}

type DeleteTripRequest struct {
	UserId int64  `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	TripId string `thrift:"tripId,2,required" frugal:"2,required,string" json:"tripId"`
}

func NewDeleteTripRequest() *DeleteTripRequest {
	return &DeleteTripRequest{}
}

func (p *DeleteTripRequest) InitDefault() {
}

func (p *DeleteTripRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *DeleteTripRequest) GetTripId() (v string) {
	return p.TripId
}
func (p *DeleteTripRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *DeleteTripRequest) SetTripId(val string) {
	p.TripId = val
}

func (p *DeleteTripRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteTripRequest(%+v)", *p)
}

var fieldIDToName_DeleteTripRequest = map[int16]string{
	1: "userId",
	2: "tripId",
}

type DeleteTripResponse struct {
	BaseResp *base.BaseResp `thrift:"baseResp,1,required" frugal:"1,required,base.BaseResp" json:"baseResp"`
}

func NewDeleteTripResponse() *DeleteTripResponse {
	return &DeleteTripResponse{}
}

func (p *DeleteTripResponse) InitDefault() {
}

var DeleteTripResponse_BaseResp_DEFAULT *base.BaseResp

func (p *DeleteTripResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return DeleteTripResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *DeleteTripResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *DeleteTripResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *DeleteTripResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteTripResponse(%+v)", *p)
}

var fieldIDToName_DeleteTripResponse = map[int16]string{
	1: "baseResp",
}

type TripService interface {
	CreateTrip(ctx context.Context, req *CreateTripRequest) (r *CreateTripResponse, err error)

	ListTrips(ctx context.Context, req *ListTripsRequest) (r *ListTripsResponse, err error)

	GetLatestTrip(ctx context.Context, req *GetLatestTripRequest) (r *GetLatestTripResponse, err error)

	GetTripDetail(ctx context.Context, req *GetTripDetailRequest) (r *GetTripDetailResponse, err error)

	DeleteTrip(ctx context.Context, req *DeleteTripRequest) (r *DeleteTripResponse, err error)
}

type TripServiceCreateTripArgs struct {
	Req *CreateTripRequest `thrift:"req,1" frugal:"1,default,CreateTripRequest" json:"req"`
}

func NewTripServiceCreateTripArgs() *TripServiceCreateTripArgs {
	return &TripServiceCreateTripArgs{}
}

func (p *TripServiceCreateTripArgs) InitDefault() {
}

var TripServiceCreateTripArgs_Req_DEFAULT *CreateTripRequest

func (p *TripServiceCreateTripArgs) GetReq() (v *CreateTripRequest) {
	if !p.IsSetReq() {
		return TripServiceCreateTripArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TripServiceCreateTripArgs) SetReq(val *CreateTripRequest) {
	p.Req = val
}

func (p *TripServiceCreateTripArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TripServiceCreateTripArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceCreateTripArgs(%+v)", *p)
}

var fieldIDToName_TripServiceCreateTripArgs = map[int16]string{
	1: "req",
}

type TripServiceCreateTripResult struct {
	Success *CreateTripResponse `thrift:"success,0,optional" frugal:"0,optional,CreateTripResponse" json:"success,omitempty"`
}

func NewTripServiceCreateTripResult() *TripServiceCreateTripResult {
	return &TripServiceCreateTripResult{}
}

func (p *TripServiceCreateTripResult) InitDefault() {
}

var TripServiceCreateTripResult_Success_DEFAULT *CreateTripResponse

func (p *TripServiceCreateTripResult) GetSuccess() (v *CreateTripResponse) {
	if !p.IsSetSuccess() {
		return TripServiceCreateTripResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TripServiceCreateTripResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateTripResponse)
}

func (p *TripServiceCreateTripResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TripServiceCreateTripResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceCreateTripResult(%+v)", *p)
}

var fieldIDToName_TripServiceCreateTripResult = map[int16]string{
	0: "success",
}

type TripServiceListTripsArgs struct {
	Req *ListTripsRequest `thrift:"req,1" frugal:"1,default,ListTripsRequest" json:"req"`
}

func NewTripServiceListTripsArgs() *TripServiceListTripsArgs {
	return &TripServiceListTripsArgs{}
}

func (p *TripServiceListTripsArgs) InitDefault() {
}

var TripServiceListTripsArgs_Req_DEFAULT *ListTripsRequest

func (p *TripServiceListTripsArgs) GetReq() (v *ListTripsRequest) {
	if !p.IsSetReq() {
		return TripServiceListTripsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TripServiceListTripsArgs) SetReq(val *ListTripsRequest) {
	p.Req = val
}

func (p *TripServiceListTripsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TripServiceListTripsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceListTripsArgs(%+v)", *p)
}

var fieldIDToName_TripServiceListTripsArgs = map[int16]string{
	1: "req",
}

type TripServiceListTripsResult struct {
	Success *ListTripsResponse `thrift:"success,0,optional" frugal:"0,optional,ListTripsResponse" json:"success,omitempty"`
}

func NewTripServiceListTripsResult() *TripServiceListTripsResult {
	return &TripServiceListTripsResult{}
}

func (p *TripServiceListTripsResult) InitDefault() {
}

var TripServiceListTripsResult_Success_DEFAULT *ListTripsResponse

func (p *TripServiceListTripsResult) GetSuccess() (v *ListTripsResponse) {
	if !p.IsSetSuccess() {
		return TripServiceListTripsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TripServiceListTripsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListTripsResponse)
}

func (p *TripServiceListTripsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TripServiceListTripsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceListTripsResult(%+v)", *p)
}

var fieldIDToName_TripServiceListTripsResult = map[int16]string{
	0: "success",
}

type TripServiceGetLatestTripArgs struct {
	Req *GetLatestTripRequest `thrift:"req,1" frugal:"1,default,GetLatestTripRequest" json:"req"`
}

func NewTripServiceGetLatestTripArgs() *TripServiceGetLatestTripArgs {
	return &TripServiceGetLatestTripArgs{}
}

func (p *TripServiceGetLatestTripArgs) InitDefault() {
}

var TripServiceGetLatestTripArgs_Req_DEFAULT *GetLatestTripRequest

func (p *TripServiceGetLatestTripArgs) GetReq() (v *GetLatestTripRequest) {
	if !p.IsSetReq() {
		return TripServiceGetLatestTripArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TripServiceGetLatestTripArgs) SetReq(val *GetLatestTripRequest) {
	p.Req = val
}

func (p *TripServiceGetLatestTripArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TripServiceGetLatestTripArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceGetLatestTripArgs(%+v)", *p)
}

var fieldIDToName_TripServiceGetLatestTripArgs = map[int16]string{
	1: "req",
}

type TripServiceGetLatestTripResult struct {
	Success *GetLatestTripResponse `thrift:"success,0,optional" frugal:"0,optional,GetLatestTripResponse" json:"success,omitempty"`
}

func NewTripServiceGetLatestTripResult() *TripServiceGetLatestTripResult {
	return &TripServiceGetLatestTripResult{}
}

func (p *TripServiceGetLatestTripResult) InitDefault() {
}

var TripServiceGetLatestTripResult_Success_DEFAULT *GetLatestTripResponse

func (p *TripServiceGetLatestTripResult) GetSuccess() (v *GetLatestTripResponse) {
	if !p.IsSetSuccess() {
		return TripServiceGetLatestTripResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TripServiceGetLatestTripResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetLatestTripResponse)
}

func (p *TripServiceGetLatestTripResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TripServiceGetLatestTripResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceGetLatestTripResult(%+v)", *p)
}

var fieldIDToName_TripServiceGetLatestTripResult = map[int16]string{
	0: "success",
}

type TripServiceGetTripDetailArgs struct {
	Req *GetTripDetailRequest `thrift:"req,1" frugal:"1,default,GetTripDetailRequest" json:"req"`
}

func NewTripServiceGetTripDetailArgs() *TripServiceGetTripDetailArgs {
	return &TripServiceGetTripDetailArgs{}
}

func (p *TripServiceGetTripDetailArgs) InitDefault() {
}

var TripServiceGetTripDetailArgs_Req_DEFAULT *GetTripDetailRequest

func (p *TripServiceGetTripDetailArgs) GetReq() (v *GetTripDetailRequest) {
	if !p.IsSetReq() {
		return TripServiceGetTripDetailArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TripServiceGetTripDetailArgs) SetReq(val *GetTripDetailRequest) {
	p.Req = val
}

func (p *TripServiceGetTripDetailArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TripServiceGetTripDetailArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceGetTripDetailArgs(%+v)", *p)
}

var fieldIDToName_TripServiceGetTripDetailArgs = map[int16]string{
	1: "req",
}

type TripServiceGetTripDetailResult struct {
	Success *GetTripDetailResponse `thrift:"success,0,optional" frugal:"0,optional,GetTripDetailResponse" json:"success,omitempty"`
}

func NewTripServiceGetTripDetailResult() *TripServiceGetTripDetailResult {
	return &TripServiceGetTripDetailResult{}
}

func (p *TripServiceGetTripDetailResult) InitDefault() {
}

var TripServiceGetTripDetailResult_Success_DEFAULT *GetTripDetailResponse

func (p *TripServiceGetTripDetailResult) GetSuccess() (v *GetTripDetailResponse) {
	if !p.IsSetSuccess() {
		return TripServiceGetTripDetailResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TripServiceGetTripDetailResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetTripDetailResponse)
}

func (p *TripServiceGetTripDetailResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TripServiceGetTripDetailResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceGetTripDetailResult(%+v)", *p)
}

var fieldIDToName_TripServiceGetTripDetailResult = map[int16]string{
	0: "success",
}

type TripServiceDeleteTripArgs struct {
	Req *DeleteTripRequest `thrift:"req,1" frugal:"1,default,DeleteTripRequest" json:"req"`
}

func NewTripServiceDeleteTripArgs() *TripServiceDeleteTripArgs {
	return &TripServiceDeleteTripArgs{}
}

func (p *TripServiceDeleteTripArgs) InitDefault() {
}

var TripServiceDeleteTripArgs_Req_DEFAULT *DeleteTripRequest

func (p *TripServiceDeleteTripArgs) GetReq() (v *DeleteTripRequest) {
	if !p.IsSetReq() {
		return TripServiceDeleteTripArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *TripServiceDeleteTripArgs) SetReq(val *DeleteTripRequest) {
	p.Req = val
}

func (p *TripServiceDeleteTripArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *TripServiceDeleteTripArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceDeleteTripArgs(%+v)", *p)
}

var fieldIDToName_TripServiceDeleteTripArgs = map[int16]string{
	1: "req",
}

type TripServiceDeleteTripResult struct {
	Success *DeleteTripResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteTripResponse" json:"success,omitempty"`
}

func NewTripServiceDeleteTripResult() *TripServiceDeleteTripResult {
	return &TripServiceDeleteTripResult{}
}

func (p *TripServiceDeleteTripResult) InitDefault() {
}

var TripServiceDeleteTripResult_Success_DEFAULT *DeleteTripResponse

func (p *TripServiceDeleteTripResult) GetSuccess() (v *DeleteTripResponse) {
	if !p.IsSetSuccess() {
		return TripServiceDeleteTripResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TripServiceDeleteTripResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteTripResponse)
}

func (p *TripServiceDeleteTripResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TripServiceDeleteTripResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TripServiceDeleteTripResult(%+v)", *p)
}

var fieldIDToName_TripServiceDeleteTripResult = map[int16]string{
	0: "success",
}
