// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package ai_agent

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/base"
)

type ChatRole int64

const (
	ChatRole_USER      ChatRole = 1
	ChatRole_ASSISTANT ChatRole = 2
)

func (p ChatRole) String() string {
	switch p {
	case ChatRole_USER:
		return "USER"
	case ChatRole_ASSISTANT:
		return "ASSISTANT"
	}
	return "<UNSET>"
}

func ChatRoleFromString(s string) (ChatRole, error) {
	switch s {
	case "USER":
		return ChatRole_USER, nil
	case "ASSISTANT":
		return ChatRole_ASSISTANT, nil
	}
	return ChatRole(0), fmt.Errorf("not a valid ChatRole string")
}

func ChatRolePtr(v ChatRole) *ChatRole { return &v }
func (p *ChatRole) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ChatRole(result.Int64)
	return
}

func (p *ChatRole) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type ChatMessage struct {
	Role    ChatRole `thrift:"role,1,required" frugal:"1,required,ChatRole" json:"role"`
	Content string   `thrift:"content,2,required" frugal:"2,required,string" json:"content"`
}

func NewChatMessage() *ChatMessage {
	return &ChatMessage{}
}

func (p *ChatMessage) InitDefault() {
}

func (p *ChatMessage) GetRole() (v ChatRole) {
	return p.Role
}

func (p *ChatMessage) GetContent() (v string) {
	return p.Content
}
func (p *ChatMessage) SetRole(val ChatRole) {
	p.Role = val
}
func (p *ChatMessage) SetContent(val string) {
	p.Content = val
}

func (p *ChatMessage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatMessage(%+v)", *p)
}

var fieldIDToName_ChatMessage = map[int16]string{
	1: "role",
	2: "content",
}

type ChatRequest struct {
	UserId  int64          `thrift:"userId,1,required" frugal:"1,required,i64" json:"userId"`
	Message string         `thrift:"message,2,required" frugal:"2,required,string" json:"message"`
	History []*ChatMessage `thrift:"history,3,optional" frugal:"3,optional,list<ChatMessage>" json:"history,omitempty"`
	TraceId *string        `thrift:"traceId,4,optional" frugal:"4,optional,string" json:"traceId,omitempty"`
}

func NewChatRequest() *ChatRequest {
	return &ChatRequest{}
}

func (p *ChatRequest) InitDefault() {
}

func (p *ChatRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *ChatRequest) GetMessage() (v string) {
	return p.Message
}

var ChatRequest_History_DEFAULT []*ChatMessage

func (p *ChatRequest) GetHistory() (v []*ChatMessage) {
	if !p.IsSetHistory() {
		return ChatRequest_History_DEFAULT
	}
	return p.History
}

var ChatRequest_TraceId_DEFAULT string

func (p *ChatRequest) GetTraceId() (v string) {
	if !p.IsSetTraceId() {
		return ChatRequest_TraceId_DEFAULT
	}
	return *p.TraceId
}
func (p *ChatRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *ChatRequest) SetMessage(val string) {
	p.Message = val
}
func (p *ChatRequest) SetHistory(val []*ChatMessage) {
	p.History = val
}
func (p *ChatRequest) SetTraceId(val *string) {
	p.TraceId = val
}

func (p *ChatRequest) IsSetHistory() bool {
	return p.History != nil
}

func (p *ChatRequest) IsSetTraceId() bool {
	return p.TraceId != nil
}

func (p *ChatRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatRequest(%+v)", *p)
}

var fieldIDToName_ChatRequest = map[int16]string{
	1: "userId",
	2: "message",
	3: "history",
	4: "traceId",
}

type ChatResponse struct {
	BaseResp    *base.BaseResp `thrift:"baseResp,1,required" frugal:"1,required,base.BaseResp" json:"baseResp"`
	Reply       *ChatMessage   `thrift:"reply,2,optional" frugal:"2,optional,ChatMessage" json:"reply,omitempty"`
	Suggestions []string       `thrift:"suggestions,3,optional" frugal:"3,optional,list<string>" json:"suggestions,omitempty"`
}

func NewChatResponse() *ChatResponse {
	return &ChatResponse{}
}

func (p *ChatResponse) InitDefault() {
}

var ChatResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ChatResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ChatResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var ChatResponse_Reply_DEFAULT *ChatMessage

func (p *ChatResponse) GetReply() (v *ChatMessage) {
	if !p.IsSetReply() {
		return ChatResponse_Reply_DEFAULT
	}
	return p.Reply
}

var ChatResponse_Suggestions_DEFAULT []string

func (p *ChatResponse) GetSuggestions() (v []string) {
	if !p.IsSetSuggestions() {
		return ChatResponse_Suggestions_DEFAULT
	}
	return p.Suggestions
}
func (p *ChatResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *ChatResponse) SetReply(val *ChatMessage) {
	p.Reply = val
}
func (p *ChatResponse) SetSuggestions(val []string) {
	p.Suggestions = val
}

func (p *ChatResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ChatResponse) IsSetReply() bool {
	return p.Reply != nil
}

func (p *ChatResponse) IsSetSuggestions() bool {
	return p.Suggestions != nil
}

func (p *ChatResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatResponse(%+v)", *p)
}

var fieldIDToName_ChatResponse = map[int16]string{
	1: "baseResp",
	2: "reply",
	3: "suggestions",
}

type PromptSuggestionsRequest struct {
	UserId *int64  `thrift:"userId,1,optional" frugal:"1,optional,i64" json:"userId,omitempty"`
	Scene  *string `thrift:"scene,2,optional" frugal:"2,optional,string" json:"scene,omitempty"`
}

func NewPromptSuggestionsRequest() *PromptSuggestionsRequest {
	return &PromptSuggestionsRequest{}
}

func (p *PromptSuggestionsRequest) InitDefault() {
}

var PromptSuggestionsRequest_UserId_DEFAULT int64

func (p *PromptSuggestionsRequest) GetUserId() (v int64) {
	if !p.IsSetUserId() {
		return PromptSuggestionsRequest_UserId_DEFAULT
	}
	return *p.UserId
}

var PromptSuggestionsRequest_Scene_DEFAULT string

func (p *PromptSuggestionsRequest) GetScene() (v string) {
	if !p.IsSetScene() {
		return PromptSuggestionsRequest_Scene_DEFAULT
	}
	return *p.Scene
}
func (p *PromptSuggestionsRequest) SetUserId(val *int64) {
	p.UserId = val
}
func (p *PromptSuggestionsRequest) SetScene(val *string) {
	p.Scene = val
}

func (p *PromptSuggestionsRequest) IsSetUserId() bool {
	return p.UserId != nil
}

func (p *PromptSuggestionsRequest) IsSetScene() bool {
	return p.Scene != nil
}

func (p *PromptSuggestionsRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PromptSuggestionsRequest(%+v)", *p)
}

var fieldIDToName_PromptSuggestionsRequest = map[int16]string{
	1: "userId",
	2: "scene",
}

type PromptSuggestionsResponse struct {
	BaseResp    *base.BaseResp `thrift:"baseResp,1,required" frugal:"1,required,base.BaseResp" json:"baseResp"`
	Suggestions []string       `thrift:"suggestions,2,optional" frugal:"2,optional,list<string>" json:"suggestions,omitempty"`
}

func NewPromptSuggestionsResponse() *PromptSuggestionsResponse {
	return &PromptSuggestionsResponse{}
}

func (p *PromptSuggestionsResponse) InitDefault() {
}

var PromptSuggestionsResponse_BaseResp_DEFAULT *base.BaseResp

func (p *PromptSuggestionsResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return PromptSuggestionsResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

var PromptSuggestionsResponse_Suggestions_DEFAULT []string

func (p *PromptSuggestionsResponse) GetSuggestions() (v []string) {
	if !p.IsSetSuggestions() {
		return PromptSuggestionsResponse_Suggestions_DEFAULT
	}
	return p.Suggestions
}
func (p *PromptSuggestionsResponse) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}
func (p *PromptSuggestionsResponse) SetSuggestions(val []string) {
	p.Suggestions = val
}

func (p *PromptSuggestionsResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *PromptSuggestionsResponse) IsSetSuggestions() bool {
	return p.Suggestions != nil
}

func (p *PromptSuggestionsResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PromptSuggestionsResponse(%+v)", *p)
}

var fieldIDToName_PromptSuggestionsResponse = map[int16]string{
	1: "baseResp",
	2: "suggestions",
}

type AIAgentService interface {
	Chat(ctx context.Context, req *ChatRequest) (r *ChatResponse, err error)

	GetPromptSuggestions(ctx context.Context, req *PromptSuggestionsRequest) (r *PromptSuggestionsResponse, err error)
}

type AIAgentServiceChatArgs struct {
	Req *ChatRequest `thrift:"req,1" frugal:"1,default,ChatRequest" json:"req"`
}

func NewAIAgentServiceChatArgs() *AIAgentServiceChatArgs {
	return &AIAgentServiceChatArgs{}
}

func (p *AIAgentServiceChatArgs) InitDefault() {
}

var AIAgentServiceChatArgs_Req_DEFAULT *ChatRequest

func (p *AIAgentServiceChatArgs) GetReq() (v *ChatRequest) {
	if !p.IsSetReq() {
		return AIAgentServiceChatArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIAgentServiceChatArgs) SetReq(val *ChatRequest) {
	p.Req = val
}

func (p *AIAgentServiceChatArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIAgentServiceChatArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIAgentServiceChatArgs(%+v)", *p)
}

var fieldIDToName_AIAgentServiceChatArgs = map[int16]string{
	1: "req",
}

type AIAgentServiceChatResult struct {
	Success *ChatResponse `thrift:"success,0,optional" frugal:"0,optional,ChatResponse" json:"success,omitempty"`
}

func NewAIAgentServiceChatResult() *AIAgentServiceChatResult {
	return &AIAgentServiceChatResult{}
}

func (p *AIAgentServiceChatResult) InitDefault() {
}

var AIAgentServiceChatResult_Success_DEFAULT *ChatResponse

func (p *AIAgentServiceChatResult) GetSuccess() (v *ChatResponse) {
	if !p.IsSetSuccess() {
		return AIAgentServiceChatResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIAgentServiceChatResult) SetSuccess(x interface{}) {
	p.Success = x.(*ChatResponse)
}

func (p *AIAgentServiceChatResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIAgentServiceChatResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIAgentServiceChatResult(%+v)", *p)
}

var fieldIDToName_AIAgentServiceChatResult = map[int16]string{
	0: "success",
}

type AIAgentServiceGetPromptSuggestionsArgs struct {
	Req *PromptSuggestionsRequest `thrift:"req,1" frugal:"1,default,PromptSuggestionsRequest" json:"req"`
}

func NewAIAgentServiceGetPromptSuggestionsArgs() *AIAgentServiceGetPromptSuggestionsArgs {
	return &AIAgentServiceGetPromptSuggestionsArgs{}
}

func (p *AIAgentServiceGetPromptSuggestionsArgs) InitDefault() {
}

var AIAgentServiceGetPromptSuggestionsArgs_Req_DEFAULT *PromptSuggestionsRequest

func (p *AIAgentServiceGetPromptSuggestionsArgs) GetReq() (v *PromptSuggestionsRequest) {
	if !p.IsSetReq() {
		return AIAgentServiceGetPromptSuggestionsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AIAgentServiceGetPromptSuggestionsArgs) SetReq(val *PromptSuggestionsRequest) {
	p.Req = val
}

func (p *AIAgentServiceGetPromptSuggestionsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AIAgentServiceGetPromptSuggestionsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIAgentServiceGetPromptSuggestionsArgs(%+v)", *p)
}

var fieldIDToName_AIAgentServiceGetPromptSuggestionsArgs = map[int16]string{
	1: "req",
}

type AIAgentServiceGetPromptSuggestionsResult struct {
	Success *PromptSuggestionsResponse `thrift:"success,0,optional" frugal:"0,optional,PromptSuggestionsResponse" json:"success,omitempty"`
}

func NewAIAgentServiceGetPromptSuggestionsResult() *AIAgentServiceGetPromptSuggestionsResult {
	return &AIAgentServiceGetPromptSuggestionsResult{}
}

func (p *AIAgentServiceGetPromptSuggestionsResult) InitDefault() {
}

var AIAgentServiceGetPromptSuggestionsResult_Success_DEFAULT *PromptSuggestionsResponse

func (p *AIAgentServiceGetPromptSuggestionsResult) GetSuccess() (v *PromptSuggestionsResponse) {
	if !p.IsSetSuccess() {
		return AIAgentServiceGetPromptSuggestionsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AIAgentServiceGetPromptSuggestionsResult) SetSuccess(x interface{}) {
	p.Success = x.(*PromptSuggestionsResponse)
}

func (p *AIAgentServiceGetPromptSuggestionsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AIAgentServiceGetPromptSuggestionsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AIAgentServiceGetPromptSuggestionsResult(%+v)", *p)
}

var fieldIDToName_AIAgentServiceGetPromptSuggestionsResult = map[int16]string{
	0: "success",
}
