// Code generated by thriftgo (0.4.5). DO NOT EDIT.

package base

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ErrorCode int64

const (
	ErrorCode_SUCCESS        ErrorCode = 0
	ErrorCode_INTERNAL_ERROR ErrorCode = 10001
	ErrorCode_PARAM_ERROR    ErrorCode = 10002
	ErrorCode_AUTH_ERROR     ErrorCode = 10003
	ErrorCode_BIZ_ERROR      ErrorCode = 10004
	ErrorCode_NOT_FOUND      ErrorCode = 10005
)

func (p ErrorCode) String() string {
	switch p {
	case ErrorCode_SUCCESS:
		return "SUCCESS"
	case ErrorCode_INTERNAL_ERROR:
		return "INTERNAL_ERROR"
	case ErrorCode_PARAM_ERROR:
		return "PARAM_ERROR"
	case ErrorCode_AUTH_ERROR:
		return "AUTH_ERROR"
	case ErrorCode_BIZ_ERROR:
		return "BIZ_ERROR"
	case ErrorCode_NOT_FOUND:
		return "NOT_FOUND"
	}
	return "<UNSET>"
}

func ErrorCodeFromString(s string) (ErrorCode, error) {
	switch s {
	case "SUCCESS":
		return ErrorCode_SUCCESS, nil
	case "INTERNAL_ERROR":
		return ErrorCode_INTERNAL_ERROR, nil
	case "PARAM_ERROR":
		return ErrorCode_PARAM_ERROR, nil
	case "AUTH_ERROR":
		return ErrorCode_AUTH_ERROR, nil
	case "BIZ_ERROR":
		return ErrorCode_BIZ_ERROR, nil
	case "NOT_FOUND":
		return ErrorCode_NOT_FOUND, nil
	}
	return ErrorCode(0), fmt.Errorf("not a valid ErrorCode string")
}

func ErrorCodePtr(v ErrorCode) *ErrorCode { return &v }
func (p *ErrorCode) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ErrorCode(result.Int64)
	return
}

func (p *ErrorCode) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type BaseResp struct {
	Code    int32   `thrift:"code,1,required" frugal:"1,required,i32" json:"code"`
	Msg     string  `thrift:"msg,2,required" frugal:"2,required,string" json:"msg"`
	TraceId *string `thrift:"traceId,3,optional" frugal:"3,optional,string" json:"traceId,omitempty"`
}

func NewBaseResp() *BaseResp {
	return &BaseResp{}
}

func (p *BaseResp) InitDefault() {
}

func (p *BaseResp) GetCode() (v int32) {
	return p.Code
}

func (p *BaseResp) GetMsg() (v string) {
	return p.Msg
}

var BaseResp_TraceId_DEFAULT string

func (p *BaseResp) GetTraceId() (v string) {
	if !p.IsSetTraceId() {
		return BaseResp_TraceId_DEFAULT
	}
	return *p.TraceId
}
func (p *BaseResp) SetCode(val int32) {
	p.Code = val
}
func (p *BaseResp) SetMsg(val string) {
	p.Msg = val
}
func (p *BaseResp) SetTraceId(val *string) {
	p.TraceId = val
}

func (p *BaseResp) IsSetTraceId() bool {
	return p.TraceId != nil
}

func (p *BaseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BaseResp(%+v)", *p)
}

var fieldIDToName_BaseResp = map[int16]string{
	1: "code",
	2: "msg",
	3: "traceId",
}
