// Code generated by Kitex v0.16.2. DO NOT EDIT.

package aiagentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	ai_agent "github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/ai_agent"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Chat": kitex.NewMethodInfo(
		chatHandler,
		newAIAgentServiceChatArgs,
		newAIAgentServiceChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPromptSuggestions": kitex.NewMethodInfo(
		getPromptSuggestionsHandler,
		newAIAgentServiceGetPromptSuggestionsArgs,
		newAIAgentServiceGetPromptSuggestionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	aIAgentServiceServiceInfo                = NewServiceInfo()
	aIAgentServiceServiceInfoForClient       = NewServiceInfoForClient()
	aIAgentServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aIAgentServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aIAgentServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aIAgentServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AIAgentService"
	handlerType := (*ai_agent.AIAgentService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ai_agent",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func chatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai_agent.AIAgentServiceChatArgs)
	realResult := result.(*ai_agent.AIAgentServiceChatResult)
	success, err := handler.(ai_agent.AIAgentService).Chat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIAgentServiceChatArgs() interface{} {
	return ai_agent.NewAIAgentServiceChatArgs()
}

func newAIAgentServiceChatResult() interface{} {
	return ai_agent.NewAIAgentServiceChatResult()
}

func getPromptSuggestionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai_agent.AIAgentServiceGetPromptSuggestionsArgs)
	realResult := result.(*ai_agent.AIAgentServiceGetPromptSuggestionsResult)
	success, err := handler.(ai_agent.AIAgentService).GetPromptSuggestions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAIAgentServiceGetPromptSuggestionsArgs() interface{} {
	return ai_agent.NewAIAgentServiceGetPromptSuggestionsArgs()
}

func newAIAgentServiceGetPromptSuggestionsResult() interface{} {
	return ai_agent.NewAIAgentServiceGetPromptSuggestionsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Chat(ctx context.Context, req *ai_agent.ChatRequest) (r *ai_agent.ChatResponse, err error) {
	var _args ai_agent.AIAgentServiceChatArgs
	_args.Req = req
	var _result ai_agent.AIAgentServiceChatResult
	if err = p.c.Call(ctx, "Chat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPromptSuggestions(ctx context.Context, req *ai_agent.PromptSuggestionsRequest) (r *ai_agent.PromptSuggestionsResponse, err error) {
	var _args ai_agent.AIAgentServiceGetPromptSuggestionsArgs
	_args.Req = req
	var _result ai_agent.AIAgentServiceGetPromptSuggestionsResult
	if err = p.c.Call(ctx, "GetPromptSuggestions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
