// Code generated by Kitex v0.16.2. DO NOT EDIT.

package aiagentservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	ai_agent "github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/ai_agent"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Chat": kitex.NewMethodInfo(
		chatHandler,
		newAIAgentServiceChatArgs,
		newAIAgentServiceChatResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ChatStream": kitex.NewMethodInfo(
		chatStreamHandler,
		newAIAgentServiceChatStreamArgs,
		newAIAgentServiceChatStreamResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"GetPromptSuggestions": kitex.NewMethodInfo(
		getPromptSuggestionsHandler,
		newAIAgentServiceGetPromptSuggestionsArgs,
		newAIAgentServiceGetPromptSuggestionsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	aIAgentServiceServiceInfo = NewServiceInfo()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aIAgentServiceServiceInfo
}

// NewServiceInfo creates a new ServiceInfo
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo()
}

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "AIAgentService"
	handlerType := (*ai_agent.AIAgentService)(nil)
	extra := map[string]interface{}{
		"PackageName": "ai_agent",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         serviceMethods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func chatHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai_agent.AIAgentServiceChatArgs)
	realResult := result.(*ai_agent.AIAgentServiceChatResult)
	success, err := handler.(ai_agent.AIAgentService).Chat(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newAIAgentServiceChatArgs() interface{} {
	return ai_agent.NewAIAgentServiceChatArgs()
}

func newAIAgentServiceChatResult() interface{} {
	return ai_agent.NewAIAgentServiceChatResult()
}

func chatStreamHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	st, err := streaming.GetServerStreamFromArg(arg)
	if err != nil {
		return err
	}
	stream := streaming.NewServerStreamingServer[ai_agent.ChatStreamChunk](st)
	req := new(ai_agent.ChatRequest)
	if err := stream.RecvMsg(ctx, req); err != nil {
		return err
	}
	return handler.(ai_agent.AIAgentService).ChatStream(ctx, req, stream)
}

func newAIAgentServiceChatStreamArgs() interface{} {
	return ai_agent.NewAIAgentServiceChatStreamArgs()
}

func newAIAgentServiceChatStreamResult() interface{} {
	return ai_agent.NewAIAgentServiceChatStreamResult()
}

func getPromptSuggestionsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ai_agent.AIAgentServiceGetPromptSuggestionsArgs)
	realResult := result.(*ai_agent.AIAgentServiceGetPromptSuggestionsResult)
	success, err := handler.(ai_agent.AIAgentService).GetPromptSuggestions(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}

func newAIAgentServiceGetPromptSuggestionsArgs() interface{} {
	return ai_agent.NewAIAgentServiceGetPromptSuggestionsArgs()
}

func newAIAgentServiceGetPromptSuggestionsResult() interface{} {
	return ai_agent.NewAIAgentServiceGetPromptSuggestionsResult()
}

type kClient struct {
	c  client.Client
	sc client.Streaming
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c:  c,
		sc: c.(client.Streaming),
	}
}

func (p *kClient) Chat(ctx context.Context, req *ai_agent.ChatRequest) (r *ai_agent.ChatResponse, err error) {
	var _args ai_agent.AIAgentServiceChatArgs
	_args.Req = req
	var _result ai_agent.AIAgentServiceChatResult
	if err = p.c.Call(ctx, "Chat", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ChatStream(ctx context.Context, req *ai_agent.ChatRequest) (AIAgentService_ChatStreamClient, error) {
	st, err := p.sc.StreamX(ctx, "ChatStream")
	if err != nil {
		return nil, err
	}
	stream := streaming.NewServerStreamingClient[ai_agent.ChatStreamChunk](st)
	if err := stream.SendMsg(ctx, req); err != nil {
		return nil, err
	}
	if err := stream.CloseSend(ctx); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) GetPromptSuggestions(ctx context.Context, req *ai_agent.PromptSuggestionsRequest) (r *ai_agent.PromptSuggestionsResponse, err error) {
	var _args ai_agent.AIAgentServiceGetPromptSuggestionsArgs
	_args.Req = req
	var _result ai_agent.AIAgentServiceGetPromptSuggestionsResult
	if err = p.c.Call(ctx, "GetPromptSuggestions", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
