// Code generated by Kitex v0.16.2. DO NOT EDIT.

package aiagentservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	ai_agent "github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/ai_agent"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Chat(ctx context.Context, req *ai_agent.ChatRequest, callOptions ...callopt.Option) (r *ai_agent.ChatResponse, err error)
	ChatStream(ctx context.Context, req *ai_agent.ChatRequest, callOptions ...streamcall.Option) (stream AIAgentService_ChatStreamClient, err error)
	GetPromptSuggestions(ctx context.Context, req *ai_agent.PromptSuggestionsRequest, callOptions ...callopt.Option) (r *ai_agent.PromptSuggestionsResponse, err error)
}

type AIAgentService_ChatStreamClient streaming.ServerStreamingClient[ai_agent.ChatStreamChunk]

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.TTHeaderStreaming))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAIAgentServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAIAgentServiceClient struct {
	*kClient
}

func (p *kAIAgentServiceClient) Chat(ctx context.Context, req *ai_agent.ChatRequest, callOptions ...callopt.Option) (r *ai_agent.ChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Chat(ctx, req)
}

func (p *kAIAgentServiceClient) ChatStream(ctx context.Context, req *ai_agent.ChatRequest, callOptions ...streamcall.Option) (stream AIAgentService_ChatStreamClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.ChatStream(ctx, req)
}

func (p *kAIAgentServiceClient) GetPromptSuggestions(ctx context.Context, req *ai_agent.PromptSuggestionsRequest, callOptions ...callopt.Option) (r *ai_agent.PromptSuggestionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPromptSuggestions(ctx, req)
}
