// Code generated by Kitex v0.16.2. DO NOT EDIT.
package aiagentservice

import (
	server "github.com/cloudwego/kitex/server"
	ai_agent "github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/ai_agent"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler ai_agent.AIAgentService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler ai_agent.AIAgentService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
