// Code generated by Kitex v0.16.2. DO NOT EDIT.

package tripservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	trip "github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/trip"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateTrip(ctx context.Context, req *trip.CreateTripRequest, callOptions ...callopt.Option) (r *trip.CreateTripResponse, err error)
	ListTrips(ctx context.Context, req *trip.ListTripsRequest, callOptions ...callopt.Option) (r *trip.ListTripsResponse, err error)
	GetLatestTrip(ctx context.Context, req *trip.GetLatestTripRequest, callOptions ...callopt.Option) (r *trip.GetLatestTripResponse, err error)
	GetTripDetail(ctx context.Context, req *trip.GetTripDetailRequest, callOptions ...callopt.Option) (r *trip.GetTripDetailResponse, err error)
	DeleteTrip(ctx context.Context, req *trip.DeleteTripRequest, callOptions ...callopt.Option) (r *trip.DeleteTripResponse, err error)
	UpdateTrip(ctx context.Context, req *trip.UpdateTripRequest, callOptions ...callopt.Option) (r *trip.UpdateTripResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kTripServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTripServiceClient struct {
	*kClient
}

func (p *kTripServiceClient) CreateTrip(ctx context.Context, req *trip.CreateTripRequest, callOptions ...callopt.Option) (r *trip.CreateTripResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTrip(ctx, req)
}

func (p *kTripServiceClient) ListTrips(ctx context.Context, req *trip.ListTripsRequest, callOptions ...callopt.Option) (r *trip.ListTripsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTrips(ctx, req)
}

func (p *kTripServiceClient) GetLatestTrip(ctx context.Context, req *trip.GetLatestTripRequest, callOptions ...callopt.Option) (r *trip.GetLatestTripResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLatestTrip(ctx, req)
}

func (p *kTripServiceClient) GetTripDetail(ctx context.Context, req *trip.GetTripDetailRequest, callOptions ...callopt.Option) (r *trip.GetTripDetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTripDetail(ctx, req)
}

func (p *kTripServiceClient) DeleteTrip(ctx context.Context, req *trip.DeleteTripRequest, callOptions ...callopt.Option) (r *trip.DeleteTripResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteTrip(ctx, req)
}

func (p *kTripServiceClient) UpdateTrip(ctx context.Context, req *trip.UpdateTripRequest, callOptions ...callopt.Option) (r *trip.UpdateTripResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateTrip(ctx, req)
}
