// Code generated by Kitex v0.16.2. DO NOT EDIT.
package tripservice

import (
	server "github.com/cloudwego/kitex/server"
	trip "github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/trip"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler trip.TripService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler trip.TripService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
