// Code generated by Kitex v0.16.2. DO NOT EDIT.

package tripservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	trip "github.com/dingzijian9527-del/Travel-Assistant/kitex_gen/trip"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateTrip": kitex.NewMethodInfo(
		createTripHandler,
		newTripServiceCreateTripArgs,
		newTripServiceCreateTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListTrips": kitex.NewMethodInfo(
		listTripsHandler,
		newTripServiceListTripsArgs,
		newTripServiceListTripsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLatestTrip": kitex.NewMethodInfo(
		getLatestTripHandler,
		newTripServiceGetLatestTripArgs,
		newTripServiceGetLatestTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTripDetail": kitex.NewMethodInfo(
		getTripDetailHandler,
		newTripServiceGetTripDetailArgs,
		newTripServiceGetTripDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteTrip": kitex.NewMethodInfo(
		deleteTripHandler,
		newTripServiceDeleteTripArgs,
		newTripServiceDeleteTripResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	tripServiceServiceInfo                = NewServiceInfo()
	tripServiceServiceInfoForClient       = NewServiceInfoForClient()
	tripServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return tripServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return tripServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return tripServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TripService"
	handlerType := (*trip.TripService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "trip",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.16.2",
		Extra:           extra,
	}
	return svcInfo
}

func createTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trip.TripServiceCreateTripArgs)
	realResult := result.(*trip.TripServiceCreateTripResult)
	success, err := handler.(trip.TripService).CreateTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTripServiceCreateTripArgs() interface{} {
	return trip.NewTripServiceCreateTripArgs()
}

func newTripServiceCreateTripResult() interface{} {
	return trip.NewTripServiceCreateTripResult()
}

func listTripsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trip.TripServiceListTripsArgs)
	realResult := result.(*trip.TripServiceListTripsResult)
	success, err := handler.(trip.TripService).ListTrips(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTripServiceListTripsArgs() interface{} {
	return trip.NewTripServiceListTripsArgs()
}

func newTripServiceListTripsResult() interface{} {
	return trip.NewTripServiceListTripsResult()
}

func getLatestTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trip.TripServiceGetLatestTripArgs)
	realResult := result.(*trip.TripServiceGetLatestTripResult)
	success, err := handler.(trip.TripService).GetLatestTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTripServiceGetLatestTripArgs() interface{} {
	return trip.NewTripServiceGetLatestTripArgs()
}

func newTripServiceGetLatestTripResult() interface{} {
	return trip.NewTripServiceGetLatestTripResult()
}

func getTripDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trip.TripServiceGetTripDetailArgs)
	realResult := result.(*trip.TripServiceGetTripDetailResult)
	success, err := handler.(trip.TripService).GetTripDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTripServiceGetTripDetailArgs() interface{} {
	return trip.NewTripServiceGetTripDetailArgs()
}

func newTripServiceGetTripDetailResult() interface{} {
	return trip.NewTripServiceGetTripDetailResult()
}

func deleteTripHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*trip.TripServiceDeleteTripArgs)
	realResult := result.(*trip.TripServiceDeleteTripResult)
	success, err := handler.(trip.TripService).DeleteTrip(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTripServiceDeleteTripArgs() interface{} {
	return trip.NewTripServiceDeleteTripArgs()
}

func newTripServiceDeleteTripResult() interface{} {
	return trip.NewTripServiceDeleteTripResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateTrip(ctx context.Context, req *trip.CreateTripRequest) (r *trip.CreateTripResponse, err error) {
	var _args trip.TripServiceCreateTripArgs
	_args.Req = req
	var _result trip.TripServiceCreateTripResult
	if err = p.c.Call(ctx, "CreateTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListTrips(ctx context.Context, req *trip.ListTripsRequest) (r *trip.ListTripsResponse, err error) {
	var _args trip.TripServiceListTripsArgs
	_args.Req = req
	var _result trip.TripServiceListTripsResult
	if err = p.c.Call(ctx, "ListTrips", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLatestTrip(ctx context.Context, req *trip.GetLatestTripRequest) (r *trip.GetLatestTripResponse, err error) {
	var _args trip.TripServiceGetLatestTripArgs
	_args.Req = req
	var _result trip.TripServiceGetLatestTripResult
	if err = p.c.Call(ctx, "GetLatestTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTripDetail(ctx context.Context, req *trip.GetTripDetailRequest) (r *trip.GetTripDetailResponse, err error) {
	var _args trip.TripServiceGetTripDetailArgs
	_args.Req = req
	var _result trip.TripServiceGetTripDetailResult
	if err = p.c.Call(ctx, "GetTripDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteTrip(ctx context.Context, req *trip.DeleteTripRequest) (r *trip.DeleteTripResponse, err error) {
	var _args trip.TripServiceDeleteTripArgs
	_args.Req = req
	var _result trip.TripServiceDeleteTripResult
	if err = p.c.Call(ctx, "DeleteTrip", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
